"""
Service for exporting meeting notes to various formats.

Supports Markdown export with professional formatting.
"""

import os
from pathlib import Path
from datetime import datetime
from models.meeting_model import Meeting


class ExportService:
    """
    Service for exporting meeting notes to files.

    Generates professional Markdown files with meeting content.
    """

    DEFAULT_EXPORT_DIR = "meeting_notes"

    def __init__(self, export_dir: str = None):
        """
        Initialize the export service.

        Args:
            export_dir: Directory to export meeting files to
        """
        self.export_dir = export_dir or self.DEFAULT_EXPORT_DIR
        self._ensure_export_dir()

    def _ensure_export_dir(self) -> None:
        """Create export directory if it doesn't exist."""
        Path(self.export_dir).mkdir(parents=True, exist_ok=True)

    def export_to_markdown(self, meeting: Meeting) -> str:
        """
        Export meeting to Markdown file.

        Args:
            meeting: Meeting instance to export

        Returns:
            Path to the created file
        """
        # Generate filename
        timestamp = meeting.created_at.strftime("%Y%m%d_%H%M%S")
        filename = f"{meeting.title.replace(' ', '_')}_{timestamp}.md"
        filepath = os.path.join(self.export_dir, filename)

        # Generate content
        content = self._generate_markdown_content(meeting)

        # Write to file
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)

        return filepath

    @staticmethod
    def _generate_markdown_content(meeting: Meeting) -> str:
        """
        Generate Markdown content for a meeting.

        Args:
            meeting: Meeting instance

        Returns:
            Markdown formatted content
        """
        content = ""

        # Title
        content += f"# {meeting.title}\n\n"

        # Metadata
        content += f"**Date:** {meeting.created_at.strftime('%Y-%m-%d %H:%M:%S')}\n"
        content += f"**Duration:** {meeting.get_duration()}\n"
        content += f"**Participants:** {', '.join(meeting.participants)}\n\n"

        # Summary
        content += "## Summary\n\n"
        if meeting.action_items or meeting.decisions or meeting.important_notes:
            content += "Meeting focused on:\n\n"
            if meeting.action_items:
                content += f"- {len(meeting.action_items)} action items identified\n"
            if meeting.decisions:
                content += f"- {len(meeting.decisions)} key decisions made\n"
            if meeting.important_notes:
                content += f"- {len(meeting.important_notes)} important notes captured\n"
            content += "\n"
        else:
            content += "General meeting discussion.\n\n"

        # Participants section
        content += "## Participants\n\n"
        for participant in meeting.participants:
            content += f"- {participant}\n"
        content += "\n"

        # Transcript
        if meeting.messages:
            content += "## Meeting Transcript\n\n"
            for message in meeting.messages:
                content += f"**{message.speaker}:** {message.content}\n\n"

        # Action Items
        if meeting.action_items:
            content += "## Action Items\n\n"
            for item in meeting.action_items:
                due = f" (Due: {item.due_date})" if item.due_date else ""
                assigned = f" - {item.assigned_to}" if item.assigned_to != "Unassigned" else ""
                content += f"- [ ] {item.description}{due}{assigned}\n"
            content += "\n"

        # Decisions
        if meeting.decisions:
            content += "## Decisions\n\n"
            for decision in meeting.decisions:
                content += f"- {decision.description}\n"
            content += "\n"

        # Important Notes
        if meeting.important_notes:
            content += "## Important Notes\n\n"
            for note in meeting.important_notes:
                category = f"[{note.category.upper()}]" if note.category else ""
                content += f"- {category} {note.description}\n"
            content += "\n"

        # Statistics
        content += "## Statistics\n\n"
        content += f"- **Total Messages:** {len(meeting.messages)}\n"
        content += f"- **Action Items:** {len(meeting.action_items)}\n"
        content += f"- **Decisions:** {len(meeting.decisions)}\n"
        content += f"- **Important Notes:** {len(meeting.important_notes)}\n"
        content += f"- **Duration:** {meeting.get_duration()}\n"
        content += f"- **Exported:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"

        # Footer
        content += "---\n"
        content += "*Generated by AI Meeting Notes Manager*\n"

        return content

