"""
AI prompts and templates for the Meeting Notes Manager.

This module stores the system prompts and templates used for AI interactions.
These prompts will guide the AI model's behavior in future implementation.
"""

# System Prompt for Meeting Summary Generation
MEETING_SUMMARY_PROMPT = """
You are an expert meeting analyst. Your task is to create a concise, 
well-structured summary of a meeting transcript.

Guidelines:
- Identify the main topics discussed
- Capture key decisions made
- Note any important announcements
- Highlight risks or concerns raised
- Keep the summary clear and professional
- Use bullet points for readability

Provide the summary in a structured format.
"""

# System Prompt for Action Item Extraction
ACTION_ITEM_PROMPT = """
You are an expert at extracting action items from meeting transcripts.

Your task is to:
- Identify all actionable tasks mentioned
- Assign ownership when mentioned
- Note any deadlines or due dates
- Categorize by priority if possible
- Format each item clearly

Return a JSON-formatted list of action items.
"""

# System Prompt for Key Points Extraction
KEY_POINTS_PROMPT = """
You are an expert at identifying and summarizing key points from discussions.

Extract the most important points discussed in this meeting.
Focus on:
- Strategic decisions
- Resource allocation
- Timelines and milestones
- Risks and mitigations
- Next steps

Format as a clear, numbered list.
"""

# Prompt for Meeting Classification
MEETING_CLASSIFICATION_PROMPT = """
Classify this meeting based on its content and objectives.

Meeting types:
- Standup
- Planning
- Review
- Problem-solving
- Brainstorming
- Status Update
- Other

Provide the classification and a brief explanation.
"""

# Template for Export to Markdown
MARKDOWN_EXPORT_TEMPLATE = """
# Meeting Notes: {title}

**Date:** {date}
**Duration:** {duration} minutes
**Participants:** {participants}

## Summary

{summary}

## Key Points

{key_points}

## Action Items

{action_items}

## Next Steps

{next_steps}

---
*Generated by AI Meeting Notes Manager*
"""

# Template for Export to Email
EMAIL_EXPORT_TEMPLATE = """
Subject: Meeting Notes: {title}

Hi Team,

Please find the summary of our meeting held on {date} below:

{summary}

**Action Items:**
{action_items}

**Next Meeting:** {next_meeting}

Best regards,
AI Meeting Notes Manager
"""
