"""Agent 4: Output & Formatting Agent.

Responsible for multi-format document generation, JSON schema building,
Markdown report generation, and domain model hydration.
"""

from datetime import datetime
from typing import Any, Dict, List
from .base_agent import BaseAgent
from ..models.meeting_model import ActionItem, Decision, ImportantNote, Meeting, Message


class OutputFormattingAgent(BaseAgent):
    """
    Agent 4 - Output & Formatting Agent.

    Transforms refined multi-agent data into domain entities, Markdown exports, and API payloads.
    """

    def __init__(self):
        super().__init__(
            name="Agent-4:OutputFormatting",
            role="Generates structured Markdown reports, JSON payloads, and domain Meeting entities.",
        )

    def process(self, context: Dict[str, Any], logs: List[str]) -> Dict[str, Any]:
        metadata = context.get("metadata", {})
        title = metadata.get("title", "AI Meeting Notes")
        executive_summary = context.get("executive_summary", "")
        refined_actions = context.get("refined_action_items", [])
        refined_decisions = context.get("refined_decisions", [])
        refined_notes = context.get("refined_notes", [])
        messages = context.get("messages", [])
        speakers = context.get("speakers", [])
        confidence_score = context.get("confidence_score", 0.90)

        logs.append("Hydrating domain Meeting object.")
        meeting_entity = Meeting(title=title, participants=speakers if speakers else ["Presenter"])
        meeting_entity.summary = executive_summary

        # Populate messages
        for msg in messages:
            meeting_entity.add_message(Message(msg["speaker"], msg["content"]))

        # Populate action items
        for act in refined_actions:
            meeting_entity.add_action_item(
                ActionItem(
                    description=act["description"],
                    assigned_to=act["owner"],
                    due_date=act["due_date"],
                )
            )

        # Populate decisions
        for dec in refined_decisions:
            meeting_entity.add_decision(
                Decision(description=dec["description"], context=dec.get("context", ""))
            )

        # Populate notes
        for note in refined_notes:
            meeting_entity.add_important_note(
                ImportantNote(description=note["description"], category=note.get("category", "General"))
            )

        logs.append("Generating Markdown export document.")
        markdown_export = self._generate_markdown(
            title=title,
            summary=executive_summary,
            actions=refined_actions,
            decisions=refined_decisions,
            notes=refined_notes,
            confidence=confidence_score,
        )

        logs.append("Building JSON response payload.")
        json_payload = {
            "id": meeting_entity.id,
            "title": title,
            "created_at": meeting_entity.created_at.isoformat(),
            "confidence_score": confidence_score,
            "executive_summary": executive_summary,
            "participants": speakers,
            "action_items": refined_actions,
            "decisions": refined_decisions,
            "important_notes": refined_notes,
            "message_count": len(messages),
        }

        return {
            "meeting_entity": meeting_entity,
            "markdown_export": markdown_export,
            "json_payload": json_payload,
        }

    @staticmethod
    def _generate_markdown(
        title: str,
        summary: str,
        actions: List[Dict[str, Any]],
        decisions: List[Dict[str, Any]],
        notes: List[Dict[str, Any]],
        confidence: float,
    ) -> str:
        """Constructs a clean Markdown report."""
        md = [
            f"# {title}",
            f"*Generated by Multi-Agent Processing Pipeline on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*",
            f"**Trust & Confidence Rating**: `{int(confidence * 100)}%`\n",
            "## Executive Summary",
            f"{summary}\n",
            "## Key Decisions",
        ]

        if decisions:
            for d in decisions:
                md.append(f"- **{d['description']}**")
        else:
            md.append("- *No explicit decisions logged.*")

        md.append("\n## Action Items")
        if actions:
            for a in actions:
                md.append(f"- [ ] **{a['description']}** (Owner: @{a['owner']}, Due: {a['due_date']})")
        else:
            md.append("- *No action items detected.*")

        md.append("\n## Important Notes & Insights")
        if notes:
            for n in notes:
                md.append(f"- [{n.get('category', 'General')}] {n['description']}")
        else:
            md.append("- *No additional notes logged.*")

        return "\n".join(md)
