"""Unit tests for the ExportService."""

import os
import tempfile
from pathlib import Path

import pytest
from src.models.meeting_model import Meeting, Message, ActionItem, Decision, ImportantNote
from src.services.export_service import ExportService


class TestExportService:
    def test_initialization_default_dir(self):
        service = ExportService()
        assert service.export_dir == "meeting_notes"

    def test_initialization_custom_dir(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            service = ExportService(export_dir=tmpdir)
            assert service.export_dir == tmpdir
            assert os.path.exists(tmpdir)

    def test_export_to_markdown_returns_path(self, sample_meeting, tmp_path):
        service = ExportService(export_dir=str(tmp_path))
        path = service.export_to_markdown(sample_meeting)
        assert os.path.exists(path)
        assert path.endswith(".md")

    def test_export_to_markdown_content_has_title(self, sample_meeting, tmp_path):
        service = ExportService(export_dir=str(tmp_path))
        path = service.export_to_markdown(sample_meeting)
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        assert "# Sprint Planning" in content

    def test_export_contains_participants(self, sample_meeting, tmp_path):
        service = ExportService(export_dir=str(tmp_path))
        path = service.export_to_markdown(sample_meeting)
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        assert "Alice" in content
        assert "Bob" in content
        assert "Charlie" in content

    def test_export_contains_action_items(self, meeting_with_action_items, tmp_path):
        service = ExportService(export_dir=str(tmp_path))
        path = service.export_to_markdown(meeting_with_action_items)
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        assert "Action Items" in content
        assert "Complete authentication module" in content

    def test_export_contains_decisions(self, meeting_with_decisions, tmp_path):
        service = ExportService(export_dir=str(tmp_path))
        path = service.export_to_markdown(meeting_with_decisions)
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        assert "Decisions" in content
        assert "Use JWT" in content

    def test_export_contains_statistics(self, sample_meeting, tmp_path):
        service = ExportService(export_dir=str(tmp_path))
        path = service.export_to_markdown(sample_meeting)
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        assert "Statistics" in content
        assert "Total Messages" in content

    def test_export_empty_meeting(self, empty_meeting, tmp_path):
        service = ExportService(export_dir=str(tmp_path))
        path = service.export_to_markdown(empty_meeting)
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        assert "# Empty Meeting" in content
        assert "General meeting discussion" in content

    def test_export_generated_by_footer(self, sample_meeting, tmp_path):
        service = ExportService(export_dir=str(tmp_path))
        path = service.export_to_markdown(sample_meeting)
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        assert "Generated by AI Meeting Notes Manager" in content

    def test_export_contains_transcript(self, sample_meeting, tmp_path):
        service = ExportService(export_dir=str(tmp_path))
        path = service.export_to_markdown(sample_meeting)
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        assert "Meeting Transcript" in content
        assert "authentication module" in content

    def test_export_with_important_notes(self, tmp_path):
        meeting = Meeting("Notes Test", ["Alice"])
        meeting.add_important_note(ImportantNote("Server risk identified", "risk"))
        service = ExportService(export_dir=str(tmp_path))
        path = service.export_to_markdown(meeting)
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        assert "Important Notes" in content
        assert "Server risk identified" in content

    def test_generate_markdown_content_static(self):
        meeting = Meeting("Static Test", ["Alice"])
        content = ExportService._generate_markdown_content(meeting)
        assert isinstance(content, str)
        assert "# Static Test" in content

    def test_export_filename_contains_title(self, sample_meeting, tmp_path):
        service = ExportService(export_dir=str(tmp_path))
        path = service.export_to_markdown(sample_meeting)
        filename = os.path.basename(path)
        assert "Sprint_Planning" in filename

    def test_export_contains_duration(self, sample_meeting, tmp_path):
        service = ExportService(export_dir=str(tmp_path))
        path = service.export_to_markdown(sample_meeting)
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        assert "Duration:" in content
